/**
 * espn-api.js
 *
 * Loads league data from data/{year}.json (generated by fetch.py).
 * Falls back to data.json for backward compatibility.
 * No ESPN API calls happen in the browser — leaguemates can view
 * the site without any login or setup.
 *
 * To refresh data:
 *   1. Run: python fetch.py
 *   2. Run: python fetch.py --year 2024 (for historical seasons)
 *   3. git add data/ data.json && git commit -m "Update" && git push
 */

/**
 * Fetch the list of available seasons by checking data/{year}.json files.
 * Returns an array of year numbers sorted descending (newest first).
 */
export async function fetchAvailableSeasons() {
  const currentYear = new Date().getFullYear();

  // Build a list of years to probe (going back to 2018)
  const yearsToCheck = [];
  for (let year = currentYear; year >= 2018; year--) {
    yearsToCheck.push(year);
  }

  // Probe all years in parallel with HEAD requests
  const results = await Promise.allSettled(
    yearsToCheck.map(year => fetch(`./data/${year}.json`, { method: 'HEAD' }))
  );

  const available = [];
  results.forEach((result, index) => {
    if (result.status === 'fulfilled' && result.value.ok) {
      available.push(yearsToCheck[index]);
    }
  });

  // Fallback: if no year-specific files found, check the legacy data.json
  if (available.length === 0) {
    const response = await fetch("./data.json", { method: 'HEAD' });
    if (response.ok) {
      const data = await (await fetch("./data.json")).json();
      available.push(data.season ?? currentYear);
    }
  }

  return available.sort((a, b) => b - a);
}

/**
 * Load full league data for a given season year.
 * Tries data/{year}.json first, then falls back to data.json.
 */
export async function fetchLeagueData(year) {
  let response;

  if (year) {
    response = await fetch(`./data/${year}.json`);
    if (!response.ok) {
      response = await fetch("./data.json");
    }
  } else {
    response = await fetch("./data.json");
  }

  if (!response.ok) {
    throw new Error(
      `Could not load league data (${response.status}). ` +
      `Run "python fetch.py" first to generate it.`
    );
  }

  const data = await response.json();

  return {
    teams: data.teams,
    schedule: data.schedule,
    settings: data.settings,
    powerRankings: data.powerRankings ?? null,
    trades: data.trades ?? [],
    meta: {
      lastUpdated: data.lastUpdated,
      season: data.season,
    },
  };
}
